# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dRDfYWnYqDy1CJ7Fk6wE7QZBAirKCk0M

# Predicción de ataque al corazón (Clasificación)

1. Preparación de Datos
2. División de los datos 70-30
3. Aprendizaje del Modelo
4. Evaluación del Modelo: matriz de confusion, P,R, ROC
5. Guardar el modelo

* El despliegue se realiza en otro jupyter_notebook
"""

#Importamos librerías básicas
import pandas as pd # manipulacion dataframes
import numpy as np  # matrices y vectores
import matplotlib.pyplot as plt #gráfica
!pip install streamlit
import streamlit

"""# 1. Preparación de Datos

"""

#Cargamos los datos
data = pd.read_excel("ataque_corazon.xlsx", sheet_name="Datos")
data.head()

data.info()

#Interfaz gráfica
#Se crea con streamlit
import streamlit as st

st.title('Predicción de ataque al corazón')

# Opciones deben coincidir con los datos con los que se hizo el aprendizaje
Age = st.slider('age', min_value=1, max_value=82, value=40, step=1) # Min/Max from data.describe()
Hypertension = st.selectbox('hypertension', ['No', 'Yes'])
Heart_Disease = st.selectbox('heart_disease', ['No', 'Yes'])
Ever_Married = st.selectbox('ever_married', ['No', 'Yes'])
Avg_Glucose_Level = st.slider('avg_glucose_level', min_value=55.0, max_value=272.0, value=100.0, step=0.1) # Min/Max from data.describe()
Smoking_Status = st.selectbox('smoking_status', ["Unknown", "'never smoked'", "'formerly smoked'", "smokes"])


# Dataframe (también deben coincidir todos los nombres y el orden)
datos = [[Age, Hypertension, Heart_Disease, Ever_Married, Avg_Glucose_Level, Smoking_Status]]

#Corrección tipos de datos
data['hypertension']=data['hypertension'].astype('category')
data['heart_disease']=data['heart_disease'].astype('category')
data['ever_married']=data['ever_married'].astype('category')
data['smoking_status']=data['smoking_status'].astype('category')
data['stroke_ataque_corazon']=data['stroke_ataque_corazon'].astype('category')
data.info()

data.describe()

#Descripción varaibles numéricas
data.plot(kind='box')

#Descripción variables categóricas
data['stroke_ataque_corazon'].value_counts().plot(kind='bar')

#Variable objetivo del 30%
#La clase minoritaria tendrá el 50% del tamaño de la clase mayoritaria, adicionando datos sintéticos
#Solo se hará hasta 25% porque está muy muy desbalanceada

from imblearn.over_sampling import SMOTE, SMOTENC
X = data.drop("stroke_ataque_corazon", axis = 1)
Y = data['stroke_ataque_corazon']

smote = SMOTENC(k_neighbors=2, categorical_features=[1,2,3,5], sampling_strategy=0.25)
X_smote, y_smote = smote.fit_resample(X,Y)

# Creamos un dataframe con los resultados (X_smote, y_smote)
data  = pd.DataFrame(columns=X_smote.columns.values, data=X_smote)
data['stroke_ataque_corazon']=y_smote
data['stroke_ataque_corazon'].value_counts().plot(kind='bar')

#Dummies para las variables predictoras
data = pd.get_dummies(data, columns=['smoking_status'], drop_first=False, dtype=int)
data = pd.get_dummies(data, columns=['hypertension','heart_disease','ever_married',], drop_first=True, dtype=int)
data.head()

#LabelEncoder para la variable objetivo
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
data["stroke_ataque_corazon"]=labelencoder.fit_transform(data["stroke_ataque_corazon"])
data.head()

"""# 2. División 70-30

"""

#División 70-30
from sklearn.model_selection import train_test_split
X = data.drop("stroke_ataque_corazon", axis = 1) # Variables predictoras
Y = data['stroke_ataque_corazon'] #Variable objetivo
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, stratify=Y) #Muestreo estratificado (mantiene proporción de target)
Y_train.value_counts().plot(kind='bar')

#target 30%
Y_test.value_counts().plot(kind='bar')

"""# 3. Aprendizaje con el 70% y Evaluación con el 30%

# **Tree**
Transformacion: discretizar, el algoritmo lo puede hacer. No se normaliza
"""

#Creación del modelo con el conjunto de entrenamiento
from sklearn.tree import DecisionTreeClassifier #DecisionTreeRegressor

modelTree = DecisionTreeClassifier(criterion='gini', min_samples_leaf=50, max_depth=10) #gini, entropy
modelTree.fit(X_train, Y_train) #70% train

from sklearn.tree import plot_tree
plt.figure(figsize=(30,20)) #Tamaño de la imagen
plot_tree(modelTree, feature_names=X_train.columns.values, class_names=[str(c) for c in labelencoder.classes_], rounded=True,  fontsize=8, filled=True)
plt.show()

#Aplicar el arbol al 30%
#Evaluación 30% (X_test)
from sklearn import metrics

Y_pred = modelTree.predict(X_test) #30% Test
print(Y_pred)

#Exactitud: Correctos/Total
exactitud=metrics.accuracy_score(y_true=Y_test, y_pred=Y_pred)
print(exactitud)

#Matriz de confusion
from sklearn import metrics

cm=metrics.confusion_matrix(y_true=Y_test, y_pred=Y_pred)
cm

#Plot de la matriz de confusion
disp=metrics.ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=labelencoder.classes_)
disp.plot()

#Precision, Recall, f1, exactitud
print(metrics.classification_report( y_true=Y_test, y_pred=Y_pred, target_names=[str(c) for c in labelencoder.classes_]))

metrics.RocCurveDisplay.from_estimator(modelTree,X_test, Y_test)

#Normalizacion las variables numéricas (las dummies no se normalizan)

from sklearn.preprocessing import MinMaxScaler
min_max_scaler = MinMaxScaler()
variables_numericas=['age','avg_glucose_level']

min_max_scaler.fit(data[variables_numericas]) #Ajuste de los parametros sobre 100% de los datos (data): max - min
#Se aplica la normalización a 70%  y 30%
X_train[variables_numericas]= min_max_scaler.transform(X_train[variables_numericas]) #70%
X_test[variables_numericas]= min_max_scaler.transform(X_test[variables_numericas]) #30%
X_train.head()


#FIT EN TOTAL TRANSFORM EN 70 Y 30

X_test.head()

#Aprendizaje KNN con 70%
from sklearn.neighbors  import KNeighborsClassifier #KNeighborsRegressor

modelKnn = KNeighborsClassifier(n_neighbors=1, metric='euclidean')#euclidean, minkowski
modelKnn.fit(X_train, Y_train) #70%

#Evaluación de Knn con 30%
from sklearn import metrics

Y_pred = modelKnn.predict(X_test) #30%

#Matriz de confusion
cm=metrics.confusion_matrix(y_true=Y_test, y_pred=Y_pred)
disp=metrics.ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=labelencoder.classes_)
disp.plot()

#Precision, Recall, f1, exactitud
print(metrics.classification_report( y_true=Y_test, y_pred=Y_pred, target_names=[str(c) for c in labelencoder.classes_]))

# Curva ROC
metrics.RocCurveDisplay.from_estimator(modelKnn,X_test, Y_test)

"""# **KNN**
* Normalización
"""



"""# **Red Neuronal**
- Normalizar
"""

from sklearn.neural_network import MLPClassifier #MLPRegressor

#Solo se configura capas ocultas, no se configura capa de entrada y de salida
#activation -> función activación de la oculta: tanh, logistic, linear, relu
#hidden_layer_sizes=5,7 -> dos capas ocultas con 5 neuronas y 7 neuronas
#learning_rate-> tamaño del paso constante o decreciente (constant, adaptive)
#learning_rate_init-> valor tasa de aprendizaje
#momentum-> valor momentum
#max_iter-> iteaciones
#random_state-> semilla para generacion numeros seudoaletorios
modelNN = MLPClassifier(activation="logistic",hidden_layer_sizes=(50), learning_rate='constant',
                     learning_rate_init=0.02, momentum= 0.03, max_iter=500, random_state=3)

modelNN.fit(X_train, Y_train) #70% normalizados

#VERIFICAR SOBREENTRENAMIENTO siempre debe ir hacia abajo
#Loss es la desviación entre Y_train y el Y_pred
loss_values = modelNN.loss_curve_
plt.plot(loss_values)

#Evaluación de Red Neuronal
from sklearn import metrics

Y_pred = modelNN.predict(X_test) #30%

#Matriz de confusion
cm=metrics.confusion_matrix(y_true=Y_test, y_pred=Y_pred)
disp=metrics.ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=labelencoder.classes_)
disp.plot()

#Precision, Recall, f1, exactitud
print(metrics.classification_report( y_true=Y_test, y_pred=Y_pred, target_names=[str(c) for c in labelencoder.classes_]))

# Curva ROC
metrics.RocCurveDisplay.from_estimator(modelNN,X_test, Y_test)

#Imprimir el modelo
print(modelNN.coefs_)  # W
print(modelNN.intercepts_) # b

"""# **SVM**
-Normalizar
"""

#SVM
from sklearn.svm import SVC # SVR

modelSVM = SVC(kernel='rbf',C=1,class_weight="balanced") #'linear', 'poly'->degree=3, 'rbf', 'sigmoid', 'precomputed'
modelSVM.fit(X_train, Y_train) #70%

#Evaluación de SVM
from sklearn import metrics

Y_pred = modelSVM.predict(X_test) #30%

#Matriz de confusion
cm=metrics.confusion_matrix(y_true=Y_test, y_pred=Y_pred)
disp=metrics.ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=labelencoder.classes_)
disp.plot()

#Precision, Recall, f1, exactitud
print(metrics.classification_report( y_true=Y_test, y_pred=Y_pred, target_names=[str(c) for c in labelencoder.classes_]))

# Curva ROC
metrics.RocCurveDisplay.from_estimator(modelSVM,X_test, Y_test)

"""# **Regresión Logística**
-Normalizar
"""

from sklearn.linear_model import LogisticRegression
# Creación del modelo de Regresión Logística
modelLR = LogisticRegression(max_iter=100, random_state=3)
modelLR.fit(X_train, Y_train) # 70% normalizados

#Evaluación de Reg logística
from sklearn import metrics

Y_pred = modelLR.predict(X_test) #30%

#Matriz de confusion
cm=metrics.confusion_matrix(y_true=Y_test, y_pred=Y_pred)
disp=metrics.ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=labelencoder.classes_)
disp.plot()

#Precision, Recall, f1, exactitud
print(metrics.classification_report( y_true=Y_test, y_pred=Y_pred, target_names=[str(c) for c in labelencoder.classes_]))

# Curva ROC
metrics.RocCurveDisplay.from_estimator(modelLR,X_test, Y_test)

"""# 5. Guardamos el mejor modelo
Se entrena modelo final con 100% de los datos (X,Y)

Selección del modelo:
"""

#Normalizar X en caso de ser necesario: Knn, NN, SVM, Reg
X[variables_numericas]= min_max_scaler.transform(X[variables_numericas])

#Entrenamos modelo final
modelKnn.fit(X, Y) #100%

import pickle
filename = 'modelo-classKNN.pkl'
variables= X.columns._values
pickle.dump([modelKnn, labelencoder,variables,min_max_scaler], open(filename, 'wb'))

