# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12QLcJM-y3iIuAs2jMBDUKKigNxqlv5_X

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import streamlit as st

import pickle
filename = 'modelo-classKNN.pkl'
modelKnn, labelencoder,variables,min_max_scaler = pickle.load(open(filename, 'rb'))

#data = pd.read_excel("ataque_cardíaco_futuros.xlsx")
#data.head()

#Interfaz gráfica
#Se crea con streamlit

st.title('Predicción de ataque al corazón')

# Opciones deben coincidir con los datos con los que se hizo el aprendizaje
Age = st.slider('age', min_value=1, max_value=82, value=40, step=1) # Min/Max from data.describe()
Hypertension = st.selectbox('hypertension', ['No', 'Yes'])
Heart_Disease = st.selectbox('heart_disease', ['No', 'Yes'])
Ever_Married = st.selectbox('ever_married', ['No', 'Yes'])
Avg_Glucose_Level = st.slider('avg_glucose_level', min_value=55.0, max_value=272.0, value=100.0, step=0.1) # Min/Max from data.describe()
Smoking_Status = st.selectbox('smoking_status', ["Unknown", "'never smoked'", "'formerly smoked'", "smokes"])


# Dataframe (también deben coincidir todos los nombres y el orden)
datos = [[age, hypertension, heart_disease, ever_married, avg_glucose_level, smoking_status]]
data = pd.DataFrame(datos, columns=['hypertension', 'heart_disease', 'ever_married', 'avg_glucose_level','smoking_status']) #Dataframe con los mismos nombres de variables


#Se realiza la preparación
data_preparada=data.copy()

#En despliegue drop_first= False
data_preparada = pd.get_dummies(data_preparada, columns=['hypertension','smoking_status', 'heart_disease','ever_married',], drop_first=True, dtype=int)
data_preparada.head()

#Se adicionan las columnas faltantes (le mando los nombres de las variables que quiero que existan)
data_preparada=data_preparada.reindex(columns=variables,fill_value=0) #Compara data preparada con las que deberia tener, si no existe la crea llenándola con 0
data_preparada.head()

#Se normaliza la edad para predecir con Knn, Red, SVM
#En los despliegues no se llama fit
data_preparada[['age','avg_glucose_level']]= min_max_scaler.transform(data_preparada[['age', 'avg_glucose_level']])
data_preparada.head()

"""Predicciones"""

#Hacemos la predicción
Y_pred = modelKnn.predict(data_preparada)
print(Y_pred)

data['Prediccion']=Y_pred
data.head()

data

#recordar medida de error del modelo
st.warning("El modelo tiene un F1-SCORE del 90%%")
